// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import BuyItemReducer from "../buy_item_reducer";
import FinishShoppingReducer from "../finish_shopping_reducer";
import MovePlantReducer from "../move_plant_reducer";
import PlaceContainerReducer from "../place_container_reducer";
import PlaceFromInventoryReducer from "../place_from_inventory_reducer";
import PlacePlantReducer from "../place_plant_reducer";
import PlacePlantFromInventoryReducer from "../place_plant_from_inventory_reducer";
import RemoveContainerReducer from "../remove_container_reducer";
import RemovePlantReducer from "../remove_plant_reducer";
import ResetRunReducer from "../reset_run_reducer";
import StartCombatReducer from "../start_combat_reducer";

export type BuyItemParams = __Infer<typeof BuyItemReducer>;
export type FinishShoppingParams = __Infer<typeof FinishShoppingReducer>;
export type MovePlantParams = __Infer<typeof MovePlantReducer>;
export type PlaceContainerParams = __Infer<typeof PlaceContainerReducer>;
export type PlaceFromInventoryParams = __Infer<typeof PlaceFromInventoryReducer>;
export type PlacePlantParams = __Infer<typeof PlacePlantReducer>;
export type PlacePlantFromInventoryParams = __Infer<typeof PlacePlantFromInventoryReducer>;
export type RemoveContainerParams = __Infer<typeof RemoveContainerReducer>;
export type RemovePlantParams = __Infer<typeof RemovePlantReducer>;
export type ResetRunParams = __Infer<typeof ResetRunReducer>;
export type StartCombatParams = __Infer<typeof StartCombatReducer>;

