// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  owner: __t.identity().primaryKey(),
  enemyName: __t.string().name("enemy_name"),
  enemyHp: __t.i32().name("enemy_hp"),
  enemyMaxHp: __t.i32().name("enemy_max_hp"),
  enemyAttack: __t.i32().name("enemy_attack"),
  enemyCooldownMs: __t.u64().name("enemy_cooldown_ms"),
  enemySecondaryEffect: __t.string().name("enemy_secondary_effect"),
  enemySecondaryStacks: __t.i32().name("enemy_secondary_stacks"),
  tick: __t.i32(),
  status: __t.string(),
  spiritEssence: __t.i32().name("spirit_essence"),
  fatigueActive: __t.bool().name("fatigue_active"),
  fatigueDamage: __t.i32().name("fatigue_damage"),
  clockTicks: __t.i32().name("clock_ticks"),
  startTimestampUs: __t.i64().name("start_timestamp_us"),
});
