// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  plantType: __t.string().name("plant_type"),
  containerId: __t.u64().name("container_id"),
  boardX: __t.i32().name("board_x"),
  boardY: __t.i32().name("board_y"),
  element: __t.string(),
  cooldownMs: __t.u64().name("cooldown_ms"),
  triggerType: __t.string().name("trigger_type"),
  primaryEffect: __t.string().name("primary_effect"),
  primaryValue: __t.i32().name("primary_value"),
  secondaryEffect: __t.string().name("secondary_effect"),
  secondaryValue: __t.i32().name("secondary_value"),
  accuracy: __t.i32(),
  critChance: __t.i32().name("crit_chance"),
  triggerCount: __t.i32().name("trigger_count"),
  plantWidth: __t.i32().name("plant_width"),
  plantHeight: __t.i32().name("plant_height"),
});
