// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  containerType: __t.string().name("container_type"),
  x: __t.i32(),
  y: __t.i32(),
  width: __t.i32(),
  height: __t.i32(),
  capacity: __t.i32(),
  soilType: __t.string().name("soil_type"),
  affinity: __t.string(),
});
