// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.1.0 (commit 6981f48b4bc1a71c8dd9bdfe5a2c343f6370243d).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import BuyItemReducer from "./buy_item_reducer";
import FinishShoppingReducer from "./finish_shopping_reducer";
import MoveContainerReducer from "./move_container_reducer";
import MovePlantReducer from "./move_plant_reducer";
import PlaceContainerReducer from "./place_container_reducer";
import PlaceFromInventoryReducer from "./place_from_inventory_reducer";
import PlacePlantReducer from "./place_plant_reducer";
import PlacePlantFromInventoryReducer from "./place_plant_from_inventory_reducer";
import RemoveContainerReducer from "./remove_container_reducer";
import RemovePlantReducer from "./remove_plant_reducer";
import RerollShopReducer from "./reroll_shop_reducer";
import ResetRunReducer from "./reset_run_reducer";
import ReturnToGroveReducer from "./return_to_grove_reducer";
import StartCombatReducer from "./start_combat_reducer";

// Import all table schema definitions
import ActiveEffectRow from "./active_effect_table";
import CombatLogEntryRow from "./combat_log_entry_table";
import CombatStateRow from "./combat_state_table";
import ContainerOnBoardRow from "./container_on_board_table";
import InventoryRow from "./inventory_table";
import PlantInContainerRow from "./plant_in_container_table";
import PlayerRow from "./player_table";
import ShopOfferRow from "./shop_offer_table";

const tablesSchema = __schema({
  active_effect: __table({
    name: 'active_effect',
    indexes: [
      { accessor: 'id', name: 'active_effect_id_idx_btree', algorithm: 'btree', columns: ['id'] },
      { accessor: 'owner', name: 'active_effect_owner_idx_btree', algorithm: 'btree', columns: ['owner'] },
    ],
    constraints: [
      { name: 'active_effect_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ActiveEffectRow),
  combat_log_entry: __table({
    name: 'combat_log_entry',
    indexes: [
      { accessor: 'id', name: 'combat_log_entry_id_idx_btree', algorithm: 'btree', columns: ['id'] },
      { accessor: 'owner', name: 'combat_log_entry_owner_idx_btree', algorithm: 'btree', columns: ['owner'] },
    ],
    constraints: [
      { name: 'combat_log_entry_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CombatLogEntryRow),
  combat_state: __table({
    name: 'combat_state',
    indexes: [
      { accessor: 'owner', name: 'combat_state_owner_idx_btree', algorithm: 'btree', columns: ['owner'] },
    ],
    constraints: [
      { name: 'combat_state_owner_key', constraint: 'unique', columns: ['owner'] },
    ],
  }, CombatStateRow),
  container_on_board: __table({
    name: 'container_on_board',
    indexes: [
      { accessor: 'id', name: 'container_on_board_id_idx_btree', algorithm: 'btree', columns: ['id'] },
      { accessor: 'owner', name: 'container_on_board_owner_idx_btree', algorithm: 'btree', columns: ['owner'] },
    ],
    constraints: [
      { name: 'container_on_board_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ContainerOnBoardRow),
  inventory: __table({
    name: 'inventory',
    indexes: [
      { accessor: 'id', name: 'inventory_id_idx_btree', algorithm: 'btree', columns: ['id'] },
      { accessor: 'owner', name: 'inventory_owner_idx_btree', algorithm: 'btree', columns: ['owner'] },
    ],
    constraints: [
      { name: 'inventory_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, InventoryRow),
  plant_in_container: __table({
    name: 'plant_in_container',
    indexes: [
      { accessor: 'container_id', name: 'plant_in_container_container_id_idx_btree', algorithm: 'btree', columns: ['containerId'] },
      { accessor: 'id', name: 'plant_in_container_id_idx_btree', algorithm: 'btree', columns: ['id'] },
      { accessor: 'owner', name: 'plant_in_container_owner_idx_btree', algorithm: 'btree', columns: ['owner'] },
    ],
    constraints: [
      { name: 'plant_in_container_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlantInContainerRow),
  player: __table({
    name: 'player',
    indexes: [
      { accessor: 'identity', name: 'player_identity_idx_btree', algorithm: 'btree', columns: ['identity'] },
    ],
    constraints: [
      { name: 'player_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  shop_offer: __table({
    name: 'shop_offer',
    indexes: [
      { accessor: 'id', name: 'shop_offer_id_idx_btree', algorithm: 'btree', columns: ['id'] },
      { accessor: 'owner', name: 'shop_offer_owner_idx_btree', algorithm: 'btree', columns: ['owner'] },
    ],
    constraints: [
      { name: 'shop_offer_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ShopOfferRow),
});

const reducersSchema = __reducers(
  __reducerSchema("buy_item", BuyItemReducer),
  __reducerSchema("finish_shopping", FinishShoppingReducer),
  __reducerSchema("move_container", MoveContainerReducer),
  __reducerSchema("move_plant", MovePlantReducer),
  __reducerSchema("place_container", PlaceContainerReducer),
  __reducerSchema("place_from_inventory", PlaceFromInventoryReducer),
  __reducerSchema("place_plant", PlacePlantReducer),
  __reducerSchema("place_plant_from_inventory", PlacePlantFromInventoryReducer),
  __reducerSchema("remove_container", RemoveContainerReducer),
  __reducerSchema("remove_plant", RemovePlantReducer),
  __reducerSchema("reroll_shop", RerollShopReducer),
  __reducerSchema("reset_run", ResetRunReducer),
  __reducerSchema("return_to_grove", ReturnToGroveReducer),
  __reducerSchema("start_combat", StartCombatReducer),
);

const proceduresSchema = __procedures();

const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.1.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}
