// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ActiveEffect = __t.object("ActiveEffect", {
  id: __t.u64(),
  owner: __t.identity(),
  target: __t.string(),  // "player" | "enemy"
  effect: __t.string(),  // "spore_rot" | "regrowth" | "bark_shield" | "bloom" |
                         // "verdant_surge" | "thorns" | "wither" | "root_chill" | "entangle"
  stacks: __t.i32(),
});
export type ActiveEffect = __Infer<typeof ActiveEffect>;

export const CombatLogEntry = __t.object("CombatLogEntry", {
  id: __t.u64(),
  owner: __t.identity(),
  tick: __t.i32(),
  message: __t.string(),
  entryType: __t.string(), // "player_attack" | "enemy_attack" | "effect" | "system" | "heal"
});
export type CombatLogEntry = __Infer<typeof CombatLogEntry>;

export const CombatState = __t.object("CombatState", {
  owner: __t.identity(),
  enemyName: __t.string(),
  enemyHp: __t.i32(),
  enemyMaxHp: __t.i32(),
  enemyAttack: __t.i32(),
  enemyCooldownMs: __t.u64(),
  enemySecondaryEffect: __t.string(),
  enemySecondaryStacks: __t.i32(),
  tick: __t.i32(),
  status: __t.string(), // "active" | "victory" | "defeat"
  spiritEssence: __t.i32(),
  fatigueActive: __t.bool(),
  fatigueDamage: __t.i32(),
  clockTicks: __t.i32(),
  startTimestampUs: __t.i64(),
});
export type CombatState = __Infer<typeof CombatState>;

export const ContainerOnBoard = __t.object("ContainerOnBoard", {
  id: __t.u64(),
  owner: __t.identity(),
  containerType: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
  width: __t.i32(),
  height: __t.i32(),
  capacity: __t.i32(),
  soilType: __t.string(),
  affinity: __t.string(),
});
export type ContainerOnBoard = __Infer<typeof ContainerOnBoard>;

export const Inventory = __t.object("Inventory", {
  id: __t.u64(),
  owner: __t.identity(),
  itemCategory: __t.string(),
  itemType: __t.string(),
});
export type Inventory = __Infer<typeof Inventory>;

export const PlantInContainer = __t.object("PlantInContainer", {
  id: __t.u64(),
  owner: __t.identity(),
  plantType: __t.string(),
  containerId: __t.u64(),
  boardX: __t.i32(),
  boardY: __t.i32(),
  element: __t.string(),
  power: __t.i32(),
  cooldownMs: __t.u64(),
  triggerType: __t.string(),    // "periodic" | "on_enemy_attack" | "passive" | "start"
  primaryEffect: __t.string(),
  primaryValue: __t.i32(),
  secondaryEffect: __t.string(),
  secondaryValue: __t.i32(),
  accuracy: __t.i32(),
  critChance: __t.i32(),
  triggerCount: __t.i32(),
  plantWidth: __t.i32(),
  plantHeight: __t.i32(),
});
export type PlantInContainer = __Infer<typeof PlantInContainer>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  hp: __t.i32(),
  maxHp: __t.i32(),
  currency: __t.i32(),
  phase: __t.string(), // "build" | "combat"
  round: __t.i32(),
  rerollCount: __t.i32(),
});
export type Player = __Infer<typeof Player>;

export const ShopOffer = __t.object("ShopOffer", {
  id: __t.u64(),
  owner: __t.identity(),
  itemCategory: __t.string(),
  itemType: __t.string(),
  cost: __t.i32(),
  purchased: __t.bool(),
  rarity: __t.string(), // "common" | "uncommon" | "rare" | "epic" | "legendary"
});
export type ShopOffer = __Infer<typeof ShopOffer>;

export const EnemyContainerOnBoard = __t.object("EnemyContainerOnBoard", {
  id: __t.u64(),
  owner: __t.identity(),
  containerType: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
  width: __t.i32(),
  height: __t.i32(),
  capacity: __t.i32(),
  soilType: __t.string(),
  affinity: __t.string(),
});
export type EnemyContainerOnBoard = __Infer<typeof EnemyContainerOnBoard>;

export const EnemyPlantInCombat = __t.object("EnemyPlantInCombat", {
  id: __t.u64(),
  owner: __t.identity(),
  plantType: __t.string(),
  containerId: __t.u64(),
  boardX: __t.i32(),
  boardY: __t.i32(),
  element: __t.string(),
  cooldownMs: __t.u64(),
  triggerType: __t.string(),
  primaryEffect: __t.string(),
  primaryValue: __t.i32(),
  secondaryEffect: __t.string(),
  secondaryValue: __t.i32(),
  accuracy: __t.i32(),
  critChance: __t.i32(),
  triggerCount: __t.i32(),
  plantWidth: __t.i32(),
  plantHeight: __t.i32(),
});
export type EnemyPlantInCombat = __Infer<typeof EnemyPlantInCombat>;
